# what are the start time, end time, and duration, of the simulation?
PREFIX saref: <https://saref.etsi.org/core/>
PREFIX woso: <https://purl.org/woso#>
SELECT ?s ?st ?et ?d WHERE {
    ?s woso:hasExecutionStartTime ?st.
    ?s woso:hasExecutionEndTime ?et.
    ?s woso:hasExecutionDuration ?d
}