# What are the start time, end time, and duration of the simulation?
PREFIX woso: <https://purl.org/woso#>
SELECT ?st ?et ?d
    WHERE {
        ?s woso:hasExecutionStartTime ?st .
        ?s woso:hasExecutionEndTime ?et .
        ?s woso:hasExecutionTime ?d .
    }