# What tool was the simulation model generated with, and when?
PREFIX woso: <https://purl.org/woso#>
SELECT ?gt ?gdt 
    WHERE { 
        ?m woso:generationTool ?gt .
        ?m woso:generationDateAndTime ?gdt .
    }