# What are the names of the simulation variables?
PREFIX woso: <https://purl.org/woso#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
SELECT ?n 
    WHERE { 
        ?s a woso:SimulationVariable ;
            rdfs:label ?n .
    }